
DART_DEFAULT_SETTINGS = {
		[1] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0.45,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "Minimap",
			["xoffset"] = {
				[1] = -974.11,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "simpleMiniMap",
					["condition"] = 81,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = 535.26,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 0.79,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0.01,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["drawlayer"] = "BACKGROUND",
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["blendmode"] = "DISABLE",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 188,
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["Backdrop"] = {
				["bottom"] = "1",
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "1.3",
				["tile"] = 1,
			},
			["scripts"] = {
			},
			["padding"] = 0,
			["alpha"] = 0.7,
			["height"] = 188,
		},
		[2] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0.6,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "Chat_links",
			["xoffset"] = {
				[1] = -424.93,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
			},
			["yoffset"] = {
				[1] = "34.4",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["drawlayer"] = "ARTWORK",
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.65",
				["bottom"] = "1",
			},
			["width"] = 290,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 0.5,
			["padding"] = 0,
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["height"] = 95,
		},
		[3] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["disablemouse"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Chat_rechts",
			["xoffset"] = {
				[1] = "424",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
						[1] = 9,
					},
					["text"] = "ChatFrame2",
					["condition"] = 50,
					["response"] = 2,
				},
				[2] = {
					["overrides"] = {
						[1] = 9,
					},
					["text"] = "ChatFrame3",
					["condition"] = 50,
					["response"] = 2,
				},
				[3] = {
					["overrides"] = {
						[1] = 9,
					},
					["text"] = "ChatFrame4",
					["condition"] = 50,
					["response"] = 2,
				},
				[4] = {
					["overrides"] = {
						[1] = 9,
					},
					["text"] = "ChatFrame5",
					["condition"] = 50,
					["response"] = 2,
				},
				[5] = {
					["overrides"] = {
						[1] = 2,
						[2] = 3,
						[3] = 4,
					},
					["text"] = "ChatFrame2",
					["condition"] = 49,
					["response"] = 1,
				},
				[6] = {
					["overrides"] = {
						[1] = 1,
						[2] = 3,
						[3] = 4,
					},
					["text"] = "ChatFrame3",
					["condition"] = 49,
					["response"] = 1,
				},
				[7] = {
					["overrides"] = {
						[1] = 1,
						[2] = 2,
						[3] = 4,
					},
					["text"] = "ChatFrame4",
					["condition"] = 49,
					["response"] = 1,
				},
				[8] = {
					["overrides"] = {
						[1] = 1,
						[2] = 2,
						[3] = 3,
					},
					["text"] = "ChatFrame5",
					["condition"] = 49,
					["response"] = 1,
				},
				[9] = {
					["overrides"] = {
					},
					["text"] = "ChatFrame1",
					["condition"] = 49,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = "34.4",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["blendmode"] = "DISABLE",
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.65",
				["bottom"] = "1",
			},
			["alpha"] = 0.5,
			["width"] = 290,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["height"] = 95,
			["borderalpha"] = 0.6,
			["scripts"] = {
			},
			["padding"] = 0,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		},
		[4] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0.6,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "Actionbars",
			["xoffset"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_2",
					["condition"] = 50,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_2",
					["condition"] = 49,
					["response"] = 2,
				},
			},
			["yoffset"] = {
				[1] = "35",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.5,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["drawlayer"] = "ARTWORK",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 263,
			["alpha"] = 0.6,
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "5",
				["left"] = "5",
				["top"] = "5",
				["tileSize"] = "1",
				["edgeSize"] = "0.7",
				["bottom"] = "5",
			},
			["height"] = 27,
			["padding"] = 0,
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
		},
		[5] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "Actionbars (2)",
			["xoffset"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_2",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_2",
					["condition"] = 50,
					["response"] = 2,
				},
				[3] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_3",
					["condition"] = 50,
					["response"] = 1,
				},
				[4] = {
					["overrides"] = {
						[1] = 1,
					},
					["text"] = "DAB_ActionBar_3",
					["condition"] = 49,
					["response"] = 2,
				},
			},
			["yoffset"] = {
				[1] = "35",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.5,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["alpha"] = 0.6,
			["width"] = 263,
			["borderalpha"] = 0.6,
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "5",
				["left"] = "5",
				["top"] = "5",
				["tileSize"] = "1",
				["edgeSize"] = "0.7",
				["bottom"] = "5",
			},
			["height"] = 48,
			["padding"] = 0,
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
		},
		[6] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "Actionbars (3)",
			["xoffset"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_3",
					["condition"] = 50,
					["response"] = 2,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_3",
					["condition"] = 49,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = 35,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.5,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["height"] = 69,
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = "1",
				["edgeSize"] = "0.7",
				["bottom"] = 5,
			},
			["width"] = 263,
			["alpha"] = 0.6,
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["padding"] = 0,
			["bgalpha"] = 0,
			["borderalpha"] = 0.6,
		},
		[7] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Petbar / ActionBar6",
			["height"] = 28,
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_6",
					["condition"] = 50,
					["response"] = 2,
				},
				[2] = {
					["overrides"] = {
						[1] = 3,
					},
					["text"] = "DAB_ActionBar_6",
					["condition"] = 49,
					["response"] = 1,
				},
				[3] = {
					["overrides"] = {
					},
					["text"] = "DAB_OtherBar_Pet",
					["condition"] = 50,
					["response"] = 2,
				},
				[4] = {
					["overrides"] = {
						[1] = 1,
					},
					["text"] = "DAB_OtherBar_Pet",
					["condition"] = 49,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = -211,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "MEDIUM",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["borderalpha"] = 0.6,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = "1",
			},
			["width"] = 290,
			["xoffset"] = {
				[1] = -425,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["highlightalpha"] = 0.3,
			["scripts"] = {
			},
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 0.5,
			["padding"] = 0,
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["bgalpha"] = 0,
		},
		[8] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["disablemouse"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Castingbar",
			["xoffset"] = {
				[1] = "0",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
						[1] = 3,
					},
					["text"] = "oCBFrame",
					["condition"] = 50,
					["response"] = 2,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "oCBFrame",
					["condition"] = 49,
					["response"] = 1,
				},
				[3] = {
					["overrides"] = {
					},
					["text"] = "oCB",
					["condition"] = 81,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = -246,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.5,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["borderalpha"] = 0.7,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["drawlayer"] = "ARTWORK",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 263,
			["alpha"] = 0.59,
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = 5,
			},
			["height"] = 24,
			["padding"] = 0,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		},
		[9] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["disablemouse"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 2,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "Fatiguebar",
			["xoffset"] = {
				[1] = "0",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
						[1] = 3,
					},
					["text"] = "oCBMirror2",
					["condition"] = 50,
					["response"] = 2,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "oCBMirror2",
					["condition"] = 49,
					["response"] = 1,
				},
				[3] = {
					["overrides"] = {
					},
					["text"] = "oCB",
					["condition"] = 81,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = -127,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.5,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["drawlayer"] = "ARTWORK",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 263,
			["alpha"] = 0.59,
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 2,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = 5,
			},
			["height"] = 24,
			["padding"] = 0,
			["bgalpha"] = 0,
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
		},
		[10] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0.6,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Actionbar 10",
			["xoffset"] = {
				[1] = 423.97,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_10",
					["condition"] = 50,
					["response"] = 2,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_10",
					["condition"] = 49,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = -211,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "MEDIUM",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 290,
			["height"] = 28,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["alpha"] = 0.5,
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = "1",
			},
			["padding"] = 0,
			["scripts"] = {
			},
			["blendmode"] = "DISABLE",
		},
		[11] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0.7,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "ChatFrameEditBox",
			["xoffset"] = {
				[1] = -425,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "ChatFrameEditBox",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "ChatFrameEditBox",
					["condition"] = 50,
					["response"] = 2,
				},
			},
			["yoffset"] = {
				[1] = -337.79,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "1",
				["bottom"] = "1",
			},
			["alpha"] = 0.55,
			["width"] = 290,
			["disablemouse"] = 1,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["padding"] = 0,
			["bgalpha"] = 0,
			["height"] = 18,
		},
		[12] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0.6,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "KTM",
			["xoffset"] = {
				[1] = 178.49,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "KLHTM_Frame",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
						[1] = 3,
					},
					["text"] = "KLHTM_Frame",
					["condition"] = 50,
					["response"] = 2,
				},
				[3] = {
					["overrides"] = {
					},
					["text"] = "KLHThreatMeter",
					["condition"] = 81,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = "34.4",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["alpha"] = 0.6,
			["width"] = 91,
			["height"] = 95,
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["tile"] = 1,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = "0",
			},
			["padding"] = 0,
			["scripts"] = {
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
		},
		[13] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0.6,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["bordercolor"] = {
				["b"] = 0.5019607843137255,
				["g"] = 0.5019607843137255,
				["r"] = 0.5019607843137255,
			},
			["name"] = "Itembar",
			["xoffset"] = {
				[1] = 251.49,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
						[1] = 4,
					},
					["text"] = "DAB_ActionBar_5",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
						[1] = 3,
					},
					["text"] = "DAB_ActionBar_4",
					["condition"] = 49,
					["response"] = 1,
				},
				[3] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_5",
					["condition"] = 50,
					["response"] = 2,
				},
				[4] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_4",
					["condition"] = 50,
					["response"] = 2,
				},
			},
			["yoffset"] = {
				[1] = "34.4",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 50,
			["height"] = 95,
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["blendmode"] = "DISABLE",
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "1",
				["bottom"] = "1",
			},
			["padding"] = 1,
			["scripts"] = {
			},
			["alpha"] = 0.6,
		},
		[14] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["disablemouse"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Mirrorbar",
			["xoffset"] = {
				[1] = "0",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "oCBMirror1",
					["condition"] = 50,
					["response"] = 2,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "oCBMirror1",
					["condition"] = 49,
					["response"] = 1,
				},
				[3] = {
					["overrides"] = {
					},
					["text"] = "oCB",
					["condition"] = 81,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = -155,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.5,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["drawlayer"] = "ARTWORK",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 263,
			["alpha"] = 0.59,
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 2,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = 5,
			},
			["height"] = 24,
			["padding"] = 0,
			["attachpoint"] = {
				[1] = 2,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordercolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 1,
			},
		},
		[15] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Itembar (3)",
			["height"] = 95,
			["Conditions"] = {
			},
			["yoffset"] = {
				[1] = "34.4",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["hide"] = true,
			["xoffset"] = {
				[1] = 240.49,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["borderalpha"] = 0.6,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = "1",
			},
			["width"] = 73,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["highlightalpha"] = 0.3,
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["alpha"] = 0.5,
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["padding"] = 0,
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
		},
		[16] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "SW Stats",
			["height"] = 119,
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "SW_BarFrame1",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "SW_BarFrame1",
					["condition"] = 50,
					["response"] = 2,
				},
				[3] = {
					["overrides"] = {
					},
					["text"] = "SW_Stats",
					["condition"] = 81,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = 338,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.25,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["borderalpha"] = 0.85,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["blendmode"] = "BLEND",
			["bgalpha"] = 0,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 300,
			["alpha"] = 0.55,
			["scripts"] = {
			},
			["highlightalpha"] = 0.3,
			["Backdrop"] = {
				["tile"] = 1,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "1",
				["bottom"] = "1",
			},
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["padding"] = 0,
			["drawlayer"] = "ARTWORK",
			["xoffset"] = {
				[1] = -402,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[17] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0.6,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "Itembar_links",
			["xoffset"] = {
				[1] = "-240",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
			},
			["yoffset"] = {
				[1] = "34.4",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["hide"] = true,
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["scripts"] = {
			},
			["alpha"] = 0.5,
			["width"] = 73,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["padding"] = 0,
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.6",
				["bottom"] = "1",
			},
			["height"] = 95,
		},
		[18] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["disablemouse"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "Grid (40)",
			["xoffset"] = {
				[1] = -276.88,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutFrame",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader8UnitButton1",
					["condition"] = 49,
					["response"] = 1,
				},
				[3] = {
					["overrides"] = {
						[1] = 4,
					},
					["text"] = "GridLayoutHeader8UnitButton1",
					["condition"] = 50,
					["response"] = 2,
				},
				[4] = {
					["overrides"] = {
					},
					["text"] = "GridEnhanced",
					["condition"] = 81,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = 82,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["borderalpha"] = 0.6,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 4,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["blendmode"] = "DISABLE",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 143,
			["alpha"] = 0.6,
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = "1",
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["scripts"] = {
			},
			["padding"] = 0,
			["drawlayer"] = "ARTWORK",
			["height"] = 95,
		},
		[19] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["disablemouse"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Grid (35)",
			["xoffset"] = {
				[1] = -276.88,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutFrame",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader8UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[3] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader7UnitButton1",
					["condition"] = 49,
					["response"] = 1,
				},
				[4] = {
					["overrides"] = {
						[1] = 2,
						[2] = 5,
					},
					["text"] = "GridLayoutHeader7UnitButton1",
					["condition"] = 50,
					["response"] = 2,
				},
				[5] = {
					["overrides"] = {
					},
					["text"] = "GridEnhanced",
					["condition"] = 81,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = 82,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["borderalpha"] = 0.6,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["attachpoint"] = {
				[1] = 4,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 128,
			["alpha"] = 0.6,
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = "1",
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["scripts"] = {
			},
			["padding"] = 0,
			["drawlayer"] = "ARTWORK",
			["height"] = 95,
		},
		[20] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["disablemouse"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "Grid (30)",
			["xoffset"] = {
				[1] = -276.88,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutFrame",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader8UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[3] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader7UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[4] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader6UnitButton1",
					["condition"] = 49,
					["response"] = 1,
				},
				[5] = {
					["overrides"] = {
						[1] = 2,
						[2] = 3,
						[3] = 6,
					},
					["text"] = "GridLayoutHeader6UnitButton1",
					["condition"] = 50,
					["response"] = 2,
				},
				[6] = {
					["overrides"] = {
					},
					["text"] = "GridEnhanced",
					["condition"] = 81,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = 82,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["borderalpha"] = 0.6,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 4,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["blendmode"] = "DISABLE",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 110,
			["alpha"] = 0.6,
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = "1",
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["scripts"] = {
			},
			["padding"] = 0,
			["drawlayer"] = "ARTWORK",
			["height"] = 95,
		},
		[21] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["disablemouse"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Grid (25)",
			["xoffset"] = {
				[1] = -276.88,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutFrame",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader8UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[3] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader7UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[4] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader6UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[5] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader5UnitButton1",
					["condition"] = 49,
					["response"] = 1,
				},
				[6] = {
					["overrides"] = {
						[1] = 2,
						[2] = 3,
						[3] = 4,
						[4] = 7,
					},
					["text"] = "GridLayoutHeader5UnitButton1",
					["condition"] = 50,
					["response"] = 2,
				},
				[7] = {
					["overrides"] = {
					},
					["text"] = "GridEnhanced",
					["condition"] = 81,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = 82,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["borderalpha"] = 0.6,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["attachpoint"] = {
				[1] = 4,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 93,
			["alpha"] = 0.6,
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = "1",
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["scripts"] = {
			},
			["padding"] = 0,
			["drawlayer"] = "ARTWORK",
			["height"] = 95,
		},
		[22] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["disablemouse"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Grid (20)",
			["xoffset"] = {
				[1] = -276.88,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutFrame",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader8UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[3] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader7UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[4] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader6UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[5] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader5UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[6] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader4UnitButton1",
					["condition"] = 49,
					["response"] = 1,
				},
				[7] = {
					["overrides"] = {
						[1] = 2,
						[2] = 3,
						[3] = 4,
						[4] = 5,
						[5] = 8,
					},
					["text"] = "GridLayoutHeader4UnitButton1",
					["condition"] = 50,
					["response"] = 2,
				},
				[8] = {
					["overrides"] = {
					},
					["text"] = "GridEnhanced",
					["condition"] = 81,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = 82,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["borderalpha"] = 0.6,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["attachpoint"] = {
				[1] = 4,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 76,
			["alpha"] = 0.6,
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = "1",
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["scripts"] = {
			},
			["padding"] = 0,
			["drawlayer"] = "ARTWORK",
			["height"] = 95,
		},
		[23] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["disablemouse"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "Grid (15)",
			["xoffset"] = {
				[1] = -276.88,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutFrame",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader8UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[3] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader7UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[4] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader6UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[5] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader5UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[6] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader4UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[7] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader3UnitButton1",
					["condition"] = 49,
					["response"] = 1,
				},
				[8] = {
					["overrides"] = {
						[1] = 2,
						[2] = 3,
						[3] = 4,
						[4] = 5,
						[5] = 6,
						[6] = 9,
					},
					["text"] = "GridLayoutHeader3UnitButton1",
					["condition"] = 50,
					["response"] = 2,
				},
				[9] = {
					["overrides"] = {
					},
					["text"] = "GridEnhanced",
					["condition"] = 81,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = 82,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["borderalpha"] = 0.6,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 4,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["blendmode"] = "DISABLE",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 59,
			["alpha"] = 0.6,
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = "1",
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["scripts"] = {
			},
			["padding"] = 0,
			["drawlayer"] = "ARTWORK",
			["height"] = 95,
		},
		[24] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["disablemouse"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Grid (10)",
			["xoffset"] = {
				[1] = -276.88,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutFrame",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader8UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[3] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader7UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[4] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader6UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[5] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader5UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[6] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader4UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[7] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader3UnitButton1",
					["condition"] = 50,
					["response"] = 1,
				},
				[8] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutHeader1UnitButton1",
					["condition"] = 49,
					["response"] = 1,
				},
				[9] = {
					["overrides"] = {
						[1] = 2,
						[2] = 3,
						[3] = 4,
						[4] = 5,
						[5] = 6,
						[6] = 7,
						[7] = 11,
					},
					["text"] = "GridLayoutHeader1UnitButton1",
					["condition"] = 50,
					["response"] = 2,
				},
				[10] = {
					["overrides"] = {
						[1] = 2,
						[2] = 3,
						[3] = 4,
						[4] = 5,
						[5] = 6,
						[6] = 7,
						[7] = 11,
					},
					["text"] = "GridLayoutHeader2UnitButton1",
					["condition"] = 50,
					["response"] = 2,
				},
				[11] = {
					["overrides"] = {
					},
					["text"] = "GridEnhanced",
					["condition"] = 81,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = 82,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["borderalpha"] = 0.6,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["attachpoint"] = {
				[1] = 4,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 41,
			["alpha"] = 0.6,
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = "1",
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["scripts"] = {
			},
			["padding"] = 0,
			["drawlayer"] = "ARTWORK",
			["height"] = 95,
		},
		[25] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["disablemouse"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 0,
			["text"] = {
				["yoffset"] = 0,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Swingtimer",
			["xoffset"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "Abar_Mhr",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "Abar_Mhr",
					["condition"] = 50,
					["response"] = 2,
				},
			},
			["yoffset"] = {
				[1] = 85,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.5,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["alpha"] = 0.6,
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["borderalpha"] = 0.6,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 263,
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "5",
				["left"] = "5",
				["top"] = "5",
				["tileSize"] = "1",
				["edgeSize"] = "0.7",
				["bottom"] = "5",
			},
			["height"] = 16,
			["hide"] = true,
			["padding"] = 0,
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
		},
		["updatespeed"] = 40,
		["INITIALIZED1.1"] = true,
		["optionsscale"] = 1,
		["INITIALIZED1.5"] = true,
		["INITIALIZED1.0d"] = true,
	}