
DART_VUI_HEALER = {
		[1] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "Minimap",
			["xoffset"] = {
				[1] = "-974",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["yoffset"] = {
				[1] = "535.",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 0.79,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0.01,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["borderalpha"] = 0.45,
			["bgalpha"] = 0,
			["height"] = 188,
			["highlightalpha"] = 0.3,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 188,
			["alpha"] = 0.7,
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["scripts"] = {
			},
			["Backdrop"] = {
				["bottom"] = "1",
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "1.3",
				["tile"] = 1,
			},
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["padding"] = 0,
			["blendmode"] = "DISABLE",
			["drawlayer"] = "BACKGROUND",
		},
		[2] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "Chat_links",
			["xoffset"] = {
				[1] = -424.93,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["yoffset"] = {
				[1] = "34.4",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["borderalpha"] = 0.7,
			["bgalpha"] = 0,
			["height"] = 95,
			["highlightalpha"] = 0.3,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.65",
				["bottom"] = "1",
			},
			["width"] = 290,
			["alpha"] = 0.5,
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["scripts"] = {
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["padding"] = 0,
			["drawlayer"] = "ARTWORK",
			["blendmode"] = "DISABLE",
		},
		[3] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["name"] = "Chat_rechts",
			["xoffset"] = {
				[1] = "424",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["yoffset"] = {
				[1] = "34.4",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["disablemouse"] = 1,
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["highlightalpha"] = 0.3,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.65",
				["bottom"] = "1",
			},
			["width"] = 290,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bgalpha"] = 0,
			["scripts"] = {
			},
			["borderalpha"] = 0.7,
			["height"] = 95,
			["padding"] = 0,
			["alpha"] = 0.5,
			["blendmode"] = "DISABLE",
		},
		[4] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "Actionbars",
			["xoffset"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_2",
					["condition"] = 50,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_2",
					["condition"] = 49,
					["response"] = 2,
				},
			},
			["yoffset"] = {
				[1] = "35",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.5,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bgalpha"] = 0,
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 263,
			["alpha"] = 0.6,
			["highlightalpha"] = 0.3,
			["height"] = 27,
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "5",
				["left"] = "5",
				["top"] = "5",
				["tileSize"] = "1",
				["edgeSize"] = "0.7",
				["bottom"] = "5",
			},
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["padding"] = 0,
			["drawlayer"] = "ARTWORK",
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		},
		[5] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "Actionbars (2)",
			["xoffset"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_2",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_2",
					["condition"] = 50,
					["response"] = 2,
				},
			},
			["yoffset"] = {
				[1] = "35",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.5,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bgalpha"] = 0,
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 263,
			["borderalpha"] = 1,
			["highlightalpha"] = 0.3,
			["height"] = 48,
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "5",
				["left"] = "5",
				["top"] = "5",
				["tileSize"] = "1",
				["edgeSize"] = "0.7",
				["bottom"] = "5",
			},
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["padding"] = 0,
			["alpha"] = 0.6,
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		},
		[6] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "Actionbars (3)",
			["xoffset"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_3",
					["condition"] = 50,
					["response"] = 2,
				},
			},
			["yoffset"] = {
				[1] = 35,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.5,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["bgalpha"] = 0,
			["disablemouse"] = 1,
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["alpha"] = 0.6,
			["Backdrop"] = {
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = "1",
				["edgeSize"] = "0.7",
				["bottom"] = 5,
			},
			["width"] = 263,
			["hide"] = true,
			["highlightalpha"] = 0.3,
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["scripts"] = {
			},
			["padding"] = 0,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["height"] = 69,
		},
		[7] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "Grid",
			["xoffset"] = {
				[1] = -204.88,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutFrame",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "GridLayoutFrame",
					["condition"] = 50,
					["response"] = 2,
				},
			},
			["yoffset"] = {
				[1] = "34.4",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hide"] = true,
			["height"] = 95,
			["disablemouse"] = 1,
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bgalpha"] = 0,
			["alpha"] = 0.6,
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 143,
			["scripts"] = {
			},
			["highlightalpha"] = 0.3,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "1",
				["bottom"] = "1",
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["padding"] = 0,
			["blendmode"] = "DISABLE",
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
		},
		[8] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["name"] = "Castingbar",
			["xoffset"] = {
				[1] = "0",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "oCBFrame",
					["condition"] = 50,
					["response"] = 2,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "oCBFrame",
					["condition"] = 49,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = -246,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.5,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["disablemouse"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bgalpha"] = 0,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 263,
			["alpha"] = 0.59,
			["highlightalpha"] = 0.3,
			["height"] = 24,
			["Backdrop"] = {
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = 5,
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["padding"] = 0,
			["drawlayer"] = "ARTWORK",
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
		},
		[9] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "Fatiguebar",
			["xoffset"] = {
				[1] = "0",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "oCBMirror2",
					["condition"] = 50,
					["response"] = 2,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "oCBMirror2",
					["condition"] = 49,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = -127,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.5,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["disablemouse"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["attachpoint"] = {
				[1] = 2,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bgalpha"] = 0,
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 263,
			["alpha"] = 0.59,
			["highlightalpha"] = 0.3,
			["height"] = 24,
			["Backdrop"] = {
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = 5,
			},
			["attachto"] = {
				[1] = 2,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["padding"] = 0,
			["drawlayer"] = "ARTWORK",
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		},
		[10] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "Actionbar 10",
			["xoffset"] = {
				[1] = 423.97,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_10",
					["condition"] = 50,
					["response"] = 2,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "DAB_ActionBar_10",
					["condition"] = 49,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = -211,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 290,
			["bgalpha"] = 0,
			["highlightalpha"] = 0.3,
			["height"] = 28,
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = "1",
			},
			["scripts"] = {
			},
			["padding"] = 0,
			["alpha"] = 0.5,
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		},
		[11] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "ChatFrameEditBox",
			["xoffset"] = {
				[1] = -425,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "ChatFrameEditBox",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "ChatFrameEditBox",
					["condition"] = 50,
					["response"] = 2,
				},
			},
			["yoffset"] = {
				[1] = -337.79,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["height"] = 18,
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bgalpha"] = 0,
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "1",
				["bottom"] = "1",
			},
			["width"] = 290,
			["disablemouse"] = 1,
			["highlightalpha"] = 0.3,
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["scripts"] = {
			},
			["padding"] = 0,
			["alpha"] = 0.55,
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		},
		[12] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["name"] = "KTM",
			["xoffset"] = {
				[1] = 179.49,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "KLHTM_Frame",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "KLHTM_Frame",
					["condition"] = 50,
					["response"] = 2,
				},
			},
			["yoffset"] = {
				[1] = "34.4",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hide"] = true,
			["height"] = 95,
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bgalpha"] = 0,
			["alpha"] = 0.6,
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 90,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["highlightalpha"] = 0.3,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["Backdrop"] = {
				["tile"] = 1,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = "0",
			},
			["scripts"] = {
			},
			["padding"] = 0,
			["blendmode"] = "DISABLE",
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		},
		[13] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "Itembar",
			["xoffset"] = {
				[1] = 251.49,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
			},
			["yoffset"] = {
				[1] = "34.4",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hide"] = true,
			["height"] = 95,
			["borderalpha"] = 0.8,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bgalpha"] = 0,
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["alpha"] = 0.6,
			["width"] = 50,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["highlightalpha"] = 0.3,
			["bordercolor"] = {
				["r"] = 0.5019607843137255,
				["g"] = 0.5019607843137255,
				["b"] = 0.5019607843137255,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "1",
				["bottom"] = "1",
			},
			["scripts"] = {
			},
			["padding"] = 1,
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
		},
		[14] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "Mirrorbar",
			["xoffset"] = {
				[1] = "0",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "oCBMirror1",
					["condition"] = 50,
					["response"] = 2,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "oCBMirror1",
					["condition"] = 49,
					["response"] = 1,
				},
			},
			["yoffset"] = {
				[1] = -155,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.5,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["disablemouse"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bgalpha"] = 0,
			["attachpoint"] = {
				[1] = 2,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 263,
			["alpha"] = 0.59,
			["highlightalpha"] = 0.3,
			["height"] = 24,
			["Backdrop"] = {
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["top"] = 5,
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = 5,
			},
			["attachto"] = {
				[1] = 2,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["padding"] = 0,
			["drawlayer"] = "ARTWORK",
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
		},
		[15] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 0.8,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bgalpha"] = 0,
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["name"] = "Itembar (3)",
			["height"] = 95,
			["Conditions"] = {
			},
			["yoffset"] = {
				[1] = "34.4",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["blendmode"] = "DISABLE",
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 73,
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["alpha"] = 0.5,
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["padding"] = 0,
			["xoffset"] = {
				[1] = 240.49,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.8",
				["bottom"] = "1",
			},
		},
		[16] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bgalpha"] = 0,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "SW Stats",
			["height"] = 119,
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["text"] = "SW_BarFrame1",
					["condition"] = 49,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["text"] = "SW_BarFrame1",
					["condition"] = 50,
					["response"] = 2,
				},
			},
			["yoffset"] = {
				[1] = "338",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.25,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["xoffset"] = {
				[1] = "-402",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["disablemouse"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["drawlayer"] = "ARTWORK",
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 300,
			["alpha"] = 0.55,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["Backdrop"] = {
				["tile"] = 1,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "1",
				["bottom"] = "1",
			},
			["highlightalpha"] = 0.3,
			["padding"] = 0,
			["blendmode"] = "BLEND",
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
		},
		[17] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["drawlayer"] = "ARTWORK",
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bordertexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["name"] = "Itembar_links",
			["xoffset"] = {
				[1] = "-240",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["Conditions"] = {
			},
			["yoffset"] = {
				[1] = "34.4",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["strata"] = "BACKGROUND",
			["scale"] = 1.53,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\!ViroUI\\Textures\\RBasic.tga",
			["borderalpha"] = 0.8,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bgalpha"] = 0,
			["Backdrop"] = {
				["tile"] = true,
				["right"] = "1",
				["left"] = "1",
				["top"] = "1",
				["tileSize"] = "1",
				["edgeSize"] = "0.6",
				["bottom"] = "1",
			},
			["alpha"] = 0.5,
			["width"] = 73,
			["height"] = 95,
			["highlightalpha"] = 0.3,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["text"] = {
				["hide"] = true,
				["drawlayer"] = "OVERLAY",
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["padding"] = 0,
			["attachto"] = {
				[1] = 8,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["blendmode"] = "DISABLE",
		},
		["INITIALIZED1.5"] = true,
		["INITIALIZED1.1"] = true,
		["optionsscale"] = 1,
		["INITIALIZED1.0d"] = true,
		["updatespeed"] = 30,
	}
	