
VUI_BAGNON = {
	["Bagnon"] = {
		["strata"] = 3,
		["parentScale"] = 0.699999988079071,
		["scale"] = 1,
		["bags"] = {
			[1] = 0,
			[2] = 1,
			[3] = 2,
			[4] = 3,
			[5] = 4,
		},
		["left"] = 1359.421164653167,
		["stayOnScreen"] = 1,
		["locked"] = 1,
		["bg"] = {
			["a"] = 0.7700000107288361,
			["r"] = 0,
			["g"] = 0,
			["b"] = 0,
		},
		["top"] = 742.4093586225283,
	},
	["showBagsAtAH"] = 1,
	["showForeverTooltips"] = 1,
	["showBankAtBank"] = 1,
	["showTooltips"] = 1,
	["Banknon"] = {
		["parentScale"] = 0.699999988079071,
		["scale"] = 1,
		["bags"] = {
			[1] = -1,
			[2] = 5,
			[3] = 6,
			[4] = 7,
			[5] = 8,
			[6] = 9,
			[7] = 10,
		},
		["left"] = 717.6652398307984,
		["stayOnScreen"] = 1,
		["locked"] = 1,
		["bg"] = {
			["a"] = 0.71,
			["r"] = 0.07058823529411765,
			["g"] = 0.07058823529411765,
			["b"] = 0.07058823529411765,
		},
		["top"] = 947.0827392127856,
	},
	["version"] = "6.9.16",
	["showBagsAtBank"] = 1,
	["qualityBorders"] = 1,
}

VUI_PRAT = {
	["namespaces"] = {
		["FontSize"] = {
			["profiles"] = {
				["Default"] = {
					["sizemode"] = "ALL",
				},
			},
		},
		["PlayerNames"] = {
			["profiles"] = {
				["Default"] = {
					["color"] = {
						["b"] = 0.5450980392156862,
						["g"] = 0.4823529411764706,
						["r"] = 0.4313725490196079,
					},
				},
			},
		},
		["PopupMessage"] = {
			["profiles"] = {
				["Default"] = {
					["on"] = false,
				},
			},
		},
		["Editbox"] = {
			["profiles"] = {
				["Default"] = {
					["undocked"] = {
						["yoff"] = -1048.163060074783,
						["xoff"] = -1.469381954137931,
						["point"] = "TOPLEFT",
						["relativePoint"] = "TOPLEFT",
					},
					["alpha"] = 0,
					["width"] = 450,
					["position"] = "UNDOCKED",
					["locked"] = true,
				},
			},
		},
		["ChannelColorMemory"] = {
			["profiles"] = {
				["Default"] = {
					["colors"] = {
						["General"] = {
							["r"] = 0.2666666824370623,
							["g"] = 0.8274510293267667,
							["b"] = 1.000000059138984,
						},
						["World"] = {
							["r"] = 0.1686274609528482,
							["g"] = 0.7411765144206584,
							["b"] = 0.3607843350619078,
						},
						["Trade"] = {
							["r"] = 1.000000059138984,
							["g"] = 0.8117647538892925,
							["b"] = 0.2745098201557994,
						},
						["world"] = {
							["r"] = 0.1686274609528482,
							["g"] = 0.7411765144206584,
							["b"] = 0.3607843350619078,
						},
					},
				},
			},
		},
	},
	["disabledModules"] = {
		["Default"] = {
			["PopupMessage"] = true,
		},
	},
}

VUI_SHT = {
	["hidetext"] = false,
	["freezing"] = false,
	["aimed"] = false,
	["borderalpha"] = {
		[1] = 1,
		[2] = 1,
		[3] = 1,
		[4] = 0,
	},
	["step"] = 0.01499999966472387,
	["jomgabbar"] = false,
	["hidetime"] = false,
	["locked"] = true,
	["impconc"] = false,
	["bg"] = {
		["a"] = 0,
		["r"] = 0,
		["g"] = 0,
		["b"] = 0,
	},
	["petIntim"] = false,
	["textures"] = {
		["Flare"] = "Interface\\Icons\\Spell_Fire_Flare",
		["Rapid Fire"] = "Interface\\Icons\\Ability_Hunter_RunningShot",
		["Jom Gabbar"] = "Interface\\Icons\\Ability_Poisons",
		["Frenzy"] = "Interface\\Icons\\Ability_Druid_ChallangingRoar",
		["Aimed Shot"] = "Interface\\Icons\\INV_Spear_07",
		["Serpent Sting"] = "Interface\\Icons\\Ability_Hunter_Quickshot",
		["Scatter Shot"] = "Interface\\Icons\\Ability_GolemStormBolt",
		["Viper Sting"] = "Interface\\Icons\\Ability_Hunter_AimedShot",
		["Scorpid Sting"] = "Interface\\Icons\\Ability_Hunter_CriticalShot",
		["Wing Clip"] = "Interface\\Icons\\Ability_Rogue_Trip",
		["Hunter's Mark"] = "Interface\\Icons\\Ability_Hunter_SniperShot",
		["Scare Beast"] = "Interface\\Icons\\Ability_Druid_Cower",
		["Expose Weakness"] = "Interface\\Icons\\Ability_Hunter_SniperShot",
		["Deterrence"] = "Interface\\Icons\\Ability_Whirlwind",
		["Kiss of the Spider"] = "Interface\\Icons\\INV_Trinket_Naxxramas04",
		["Earthstrike"] = "Interface\\Icons\\Spell_Nature_AbolishMagic",
		["Zandalarian Hero Medallion"] = "Interface\\Icons\\INV_Jewelry_Necklace_13",
		["Immolation Trap"] = "Interface\\Icons\\Spell_Fire_FlameShock",
		["Counterattack"] = "Interface\\Icons\\Ability_Warrior_Challange",
		["Entrapment"] = "Interface\\Icons\\Spell_Nature_StrangleVines",
		["Primal Blessing"] = "Interface\\Icons\\Ability_Hunter_Harass",
		["Intimidation"] = "Interface\\Icons\\Ability_Devour",
		["Badge of the Swarmguard"] = "INV_Misc_AhnQirajTrinket_04",
		["Frost Trap"] = "Interface\\Icons\\Spell_Frost_FreezingBreath",
		["Auto Shot"] = "Interface\\Icons\\INV_Weapon_Crossbow_09",
		["Devilsaur Eye"] = "Interface\\Icons\\Ability_Hunter_Pet_Raptor",
		["Explosive Trap"] = "Interface\\Icons\\Spell_Fire_SelfDestruct",
		["Concussive Shot"] = "Interface\\Icons\\Spell_Frost_Stun",
		["Freezing Trap"] = "Interface\\Icons\\Spell_Frost_ChainsOfIce",
		["Quick Shots"] = "Interface\\Icons\\Ability_Warrior_InnerRage",
	},
	["wyvern"] = false,
	["spider"] = false,
	["quicktime"] = 22540.74,
	["sticky"] = true,
	["overallalpha"] = 1,
	["gap"] = true,
	["rapidtime"] = 12296.544,
	["bardistance"] = 10,
	["largetex"] = true,
	["timecolor"] = {
		[1] = 0.9999978030100465,
		[2] = 0.8196060657501221,
		[3] = 0,
		[4] = 1,
	},
	["berserking"] = false,
	["append"] = false,
	["skills"] = {
		["Earthstrike"] = true,
		["Rapid Fire"] = true,
		["Jom Gabbar"] = true,
		["Entrapment"] = true,
		["Aimed Shot"] = true,
		["Counterattack"] = true,
		["Badge of the Swarmguard"] = true,
		["Frost Trap"] = true,
		["Explosive Trap"] = true,
		["Concussive Shot"] = true,
		["Freezing Trap"] = true,
		["Flare"] = true,
		["Auto Shot"] = true,
		["Frenzy"] = true,
		["Scatter Shot"] = true,
		["Viper Sting"] = true,
		["Scorpid Sting"] = true,
		["Scare Beast"] = true,
		["Hunter's Mark"] = true,
		["Primal Blessing"] = true,
		["Zandalarian Hero Medallion"] = true,
		["Wyvern Sting"] = true,
		["Bestial Wrath"] = true,
		["Devilsaur Eye"] = true,
		["Intimidation"] = true,
		["Quick Shots"] = true,
		["Serpent Sting"] = true,
		["Deterrence"] = true,
		["Berserking"] = true,
		["Expose Weakness"] = true,
		["Kiss of the Spider"] = true,
		["Wing Clip"] = true,
		["Immolation Trap"] = true,
	},
	["primalblessing"] = false,
	["traptimemult"] = 1,
	["intimidate"] = false,
	["barheight"] = 12,
	["deterrence"] = false,
	["numBars"] = 0,
	["scale"] = 1.049999982118607,
	["earthstrike"] = false,
	["barstartcolor"] = {
		[1] = 0.1333333333333333,
		[2] = 0.1294117647058823,
		[3] = 0.1254901960784314,
		[4] = 0.8299999982118607,
	},
	["flash"] = 5,
	["on"] = true,
	["wingclip"] = false,
	["zhm"] = false,
	["quick"] = false,
	["fearbeast"] = false,
	["concuss"] = false,
	["huntersmark"] = false,
	["impwing"] = false,
	["shotdelay"] = 200,
	["exposeweak"] = false,
	["swarmguard"] = false,
	["scatter"] = false,
	["aimeddelay"] = 200,
	["colorchange"] = false,
	["targetcolor"] = {
		[1] = 0.9999978030100465,
		[2] = 0.8196060657501221,
		[3] = 0,
		[4] = 1,
	},
	["mili"] = 2,
	["entrapment"] = false,
	["devilsaur"] = false,
	["rapid"] = false,
	["showtex"] = true,
	["bardelta"] = {
		[1] = 0.6666666666666667,
		[2] = -0.1294117647058823,
		[3] = -0.1254901960784314,
		[4] = 0.1700000017881393,
	},
	["padding"] = true,
	["down"] = false,
	["skillcolor"] = {
		[1] = 0.9999978030100465,
		[2] = 0.8196060657501221,
		[3] = 0,
		[4] = 1,
	},
}

VUI_BIGWIGS = {
	["disabledModules"] = {
		["Default"] = {
			["High Priestess Jeklik"] = true,
			["Ragnaros"] = true,
			["Buru the Gorger"] = true,
			["Thaddius Arrows"] = true,
			["Anubisath Defender"] = true,
			["Ossirian the Unscarred"] = true,
			["Anubisath Guardian"] = true,
			["Grand Widow Faerlina"] = true,
			["High Priestess Mar'li"] = true,
			["Majordomo Executus"] = true,
			["High Priest Venoxis"] = true,
			["The Twin Emperors"] = true,
			["Taerar"] = true,
			["Vaelastrasz the Corrupt"] = true,
			["High Priest Thekal"] = true,
			["Noth the Plaguebringer"] = true,
			["Bloodlord Mandokir"] = true,
			["Moam"] = true,
			["The Prophet Skeram"] = true,
			["Sapphiron"] = true,
			["C'Thun"] = true,
			["General Rajaxx"] = true,
			["Princess Huhuran"] = true,
			["Thaddius"] = true,
			["Ouro"] = true,
			["Ayamiss the Hunter"] = true,
			["Ebonroc"] = true,
			["The Bug Family"] = true,
			["Heigan the Unclean"] = true,
			["Onyxia"] = true,
			["Baron Geddon"] = true,
			["High Priestess Arlokk"] = true,
			["Firemaw"] = true,
			["Jin'do the Hexxer"] = true,
			["Loatheb"] = true,
			["Gothik the Harvester"] = true,
			["Shazzrah"] = true,
			["Gluth"] = true,
			["Battleguard Sartura"] = true,
			["Lethon"] = true,
			["Kel'Thuzad"] = true,
			["Nefarian"] = true,
			["Fankriss the Unyielding"] = true,
			["Lucifron"] = true,
			["Anub'Rekhan"] = true,
			["Azuregos"] = true,
			["Lord Kazzak"] = true,
			["Razorgore the Untamed"] = true,
			["Maexxna"] = true,
			["Gehennas"] = true,
			["Hakkar"] = true,
			["The Four Horsemen"] = true,
			["Ysondre"] = true,
			["Grobbulus"] = true,
			["Instructor Razuvious"] = true,
			["Emeriss"] = true,
			["Magmadar"] = true,
			["Broodlord Lashlayer"] = true,
			["Viscidus"] = true,
			["Patchwerk"] = true,
			["Sulfuron Harbinger"] = true,
			["Flamegor"] = true,
			["Chromaggus"] = true,
			["Garr"] = true,
		},
	},
	["namespaces"] = {
		["Thaddius Arrows"] = {
			["profiles"] = {
				["Default"] = {
					["strat"] = "Run Through",
					["text"] = false,
					["sound"] = false,
					["graphic"] = false,
				},
			},
		},
		["Bars"] = {
			["profiles"] = {
				["Default"] = {
					["posx"] = 554.6132231637746,
					["posy"] = 284.2054403503029,
					["growup"] = true,
				},
			},
		},
	},
}

VUI_FUBAR_BIGWIGS = {
	["profiles"] = {
		["Default"] = {
			["detachedTooltip"] = {
			},
			["showText"] = false,
		},
	},
}

VUI_FUBAR = {
	["profiles"] = {
		["Default"] = {
			["fontSize"] = 12,
			["adjust"] = true,
			["panels"] = {
				[1] = {
					["xPercent"] = 0,
					["attachPoint"] = "TOP",
					["lock"] = true,
					["plugins"] = {
						["center"] = {
							[1] = "PerformanceFu",
							[2] = "DurabilityFu",
						},
						["right"] = {
							[1] = "ClockFu",
							[2] = "VolumeFu",
							[3] = "MoneyFu",
							[4] = "MailFu",
						},
						["left"] = {
							[1] = "LocationFu",
							[2] = "ExperienceFu",
							[3] = "Big Wigs",
							[4] = "ModMenuTuFu",
							[5] = "Grid",
							[6] = "BigWigs <WiP> edition",
							[7] = "ItemBonusesFu",
							[8] = "BigWigs <Feenix WoW> edition",
							[9] = "MetaMap",
							[10] = "FuXPFu",
							[11] = "GridEnhanced (0.11)",
							[12] = "BigWigs Mesmerize edition",
							[13] = "oRA2",
							[14] = "AtlasFu2",
						},
					},
					["widthPercent"] = 1,
					["yPercent"] = 0.983593810016236,
				},
			},
			["minimap"] = {
			},
			["skin"] = "Interface\\AddOns\\FuTextures\\blackorange",
			["centerSpacing"] = 20,
			["loadOnDemand"] = {
				["Fubar_AtlasFu2"] = {
					["title"] = "AtlasFu2",
					["category"] = "Map",
				},
				["FuBar_ClockFu"] = {
					["title"] = "ClockFu",
					["category"] = "Interface Enhancements",
				},
				["FuBar_PerformanceFu"] = {
					["title"] = "PerformanceFu",
					["category"] = "Interface Enhancements",
				},
				["FuBar_DurabilityFu"] = {
					["title"] = "DurabilityFu",
					["category"] = "Inventory",
				},
			},
			["tooltip"] = {
				["fontSizePercent"] = 1,
			},
			["rightSpacing"] = 20,
			["detached"] = {
			},
			["thickness"] = 7,
			["transparency"] = 0.5,
			["overflow"] = false,
			["places"] = {
				["center"] = {
				},
				["right"] = {
				},
				["left"] = {
				},
			},
			["leftSpacing"] = 20,
		},
	},
}

VUI_OCB = {
			["MirrorBar"] = {
				["edgeFile"] = "None",
				["height"] = 28,
				["width"] = 386,
				["texture"] = "Striped",
			},
			["Colors"] = {
				["Channel"] = {
					["r"] = 0.4117647058823529,
					["g"] = 0.4117647058823529,
					["b"] = 0.4117647058823529,
				},
				["Casting"] = {
					["r"] = 0.4117647058823529,
					["g"] = 0.4117647058823529,
					["b"] = 0.4117647058823529,
				},
				["Complete"] = {
					["r"] = 0.2901960784313726,
					["g"] = 0.2901960784313726,
					["b"] = 0.2901960784313726,
				},
			},
			["lock"] = true,
			["CastingBar"] = {
				["edgeFile"] = "None",
				["height"] = 29,
				["width"] = 385,
				["texture"] = "Striped",
			},
			["Pos"] = {
				["CastingBar"] = "476.65164147611 139.42955502291",
				["BREATH"] = "476.31578911158 606.05143620858",
				["EXHAUSTION"] = "476.34304625668 635.26978579633",
			},
}

VUI_BUFFALO = {
			["growHorizontalFirst"] = {
				["buff"] = false,
			},
			["xPos"] = {
				["debuff"] = 1598.498504292984,
				["buff"] = 1687.314909041937,
				["weapon"] = 492.9955004730074,
			},
			["scale"] = {
				["debuff"] = 1.1,
				["buff"] = 1.1,
				["weapon"] = 0.9,
			},
			["rows"] = {
				["buff"] = 16,
			},
			["cols"] = {
				["buff"] = 2,
			},
			["yPos"] = {
				["debuff"] = 1008.865194621148,
				["buff"] = 1008.865194621148,
				["weapon"] = 324.3432978485844,
			},
			["whiteTimers"] = {
				["debuff"] = true,
				["buff"] = true,
				["weapon"] = true,
			},
			["locked"] = true,
			["padding"] = {
				["debuff"] = {
					["y"] = 10,
				},
				["buff"] = {
					["y"] = 10,
				},
			},
			["growRight"] = {
				["weapon"] = true,
			},
			["verboseTimers"] = {
				["weapon"] = true,
				["buff"] = true,
			},
}

VUI_EQL3 = {
		["LockTracker"] = 1,
		["AddNew"] = 1,
		["InfoOnQuestCompletion"] = 1,
		["CustomTooltipColor"] = 0,
		["RestoreUponSelect"] = 1,
		["WindowState"] = 0,
		["LockPoints"] = {
			["corner"] = "TOPLEFT",
			["pointone"] = 4.971462884332108,
			["pointtwo"] = 891.1023778575054,
		},
		["TrackerSymbol"] = 3,
		["FadeObjectiveColor"] = 0,
		["OnlyLevelsInLog"] = 0,
		["RemoveFinished"] = 1,
		["TrackerList"] = 0,
		["FadeHeaderColor"] = 0,
		["UseTrackerListing"] = 0,
		["AddUntracked"] = 0,
		["CustomObjetiveColor"] = 0,
		["CustomTrackerBGColor"] = 0,
		["SortTrackerItems"] = 0,
		["ShowObjectiveMarkers"] = 1,
		["TrackerIsMinimized"] = 0,
		["ShowQuestLevels"] = 1,
		["TrackerFontHeight"] = 12,
		["OrganizerSettings"] = {
		},
		["CustomZoneColor"] = 0,
		["QuestWatches"] = {
		},
		["LockQuestLog"] = 1,
		["MinimizeFinished"] = 0,
		["MinimizeUponClose"] = 1,
		["CustomHeaderColor"] = 0,
		["CompletedQuests"] = {
			["The Twilight Mystery"] = {
				["isOk"] = false,
			},
			["Fight for Warsong Gulch"] = {
				["isOk"] = false,
			},
			["Special"] = {
				["isOk"] = false,
			},
			["Blackrock Spire"] = {
				["isOk"] = false,
			},
			["Bor Wildmane"] = {
				["isOk"] = false,
			},
			["Conqueror's Greaves"] = {
				["isOk"] = false,
			},
			["Arathi Basin"] = {
				["isOk"] = false,
			},
			["Bijou's Belongings"] = {
				["isOk"] = false,
			},
			["The Battle for Arathi Basin!"] = {
				["isOk"] = false,
			},
			["Icebane Gauntlets"] = {
				["isOk"] = false,
			},
			["Warsong Gulch"] = {
				["isOk"] = false,
			},
			["Conqueror's Legguards"] = {
				["isOk"] = false,
			},
			["Conqueror's Breastplate"] = {
				["isOk"] = false,
			},
			["Membership Card Renewal"] = {
				["isOk"] = false,
			},
			["Ahn'Qiraj"] = {
				["isOk"] = false,
			},
			["Finkle Einhorn, At Your Service!"] = {
				["isOk"] = false,
			},
			["Silithus"] = {
				["isOk"] = false,
			},
			["The Only Song I Know..."] = {
				["isOk"] = false,
			},
			["Engineering"] = {
				["isOk"] = false,
			},
			["Naxxramas"] = {
				["isOk"] = false,
			},
			["A Warden of the Alliance"] = {
				["isOk"] = false,
			},
			["A Humble Offering"] = {
				["isOk"] = false,
			},
		},
		["TrackerShowMinimizer"] = 0,
		["LogOpacity"] = 1,
		["ShowZonesInTracker"] = 1,
		["AutoCompleteQuests"] = 0,
		["Color"] = {
			["TrackerBG"] = {
				["a"] = 0,
				["r"] = 0.09,
				["g"] = 0.09,
				["b"] = 0.19,
			},
			["Zone"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["ObjectiveComplete"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["ObjectiveEmpty"] = {
				["r"] = 0.8,
				["g"] = 0.8,
				["b"] = 0.8,
			},
			["HeaderEmpty"] = {
				["r"] = 0.75,
				["g"] = 0.61,
				["b"] = 0,
			},
			["Tooltip"] = {
				["r"] = 1,
				["g"] = 0.8,
				["b"] = 0,
			},
			["HeaderComplete"] = {
				["r"] = 1,
				["g"] = 0.82,
				["b"] = 0,
			},
		},
		["MobTooltip"] = 0,
		["ItemTooltip"] = 0,
		["RemoveCompletedObjectives"] = 1,
		["HeaderList"] = {
		},
	}

VUI_OMNICC = {
	["vlong"] = {
		["s"] = 0.6,
		["r"] = 0.8,
		["g"] = 0.8,
		["b"] = 0.9,
	},
	["short"] = {
		["s"] = 1.3,
		["r"] = 1,
		["g"] = 0,
		["b"] = 0,
	},
	["min"] = 0,
	["font"] = "Fonts\\FRIZQT__.TTF",
	["version"] = "6.8.30",
	["size"] = 20,
	["shine"] = 1,
	["long"] = {
		["s"] = 0.8,
		["r"] = 0.8,
		["g"] = 0.8,
		["b"] = 0.9,
	},
	["shineScale"] = 6,
	["medium"] = {
		["s"] = 1,
		["r"] = 1,
		["g"] = 1,
		["b"] = 0.4,
	},
}

VUI_FUBAR_ATLAS = {
	["profiles"] = {
		["Default"] = {
			["detachedTooltip"] = {
			},
			["showText"] = false,
		},
	},
}

VUI_FUBAR_CLOCK = {
	["profiles"] = {
		["Default"] = {
			["detachedTooltip"] = {
			},
			["twentyFour"] = true,
		},
	},
}

VUI_FUBAR_DURABILITY = {
	["profiles"] = {
		["Default"] = {
			["detachedTooltip"] = {
			},
		},
	},
}

VUI_FUBAR_XP = {
	["profiles"] = {
		["Default"] = {
			["Shadow"] = false,
			["detachedTooltip"] = {
			},
			["Thickness"] = 4,
			["showText"] = false,
			["Rest"] = {
				[1] = 0.2509803921568627,
				[2] = 0.4862745098039216,
			},
			["XP"] = {
				[1] = 0.792156862745098,
				[2] = 0.792156862745098,
				[3] = 0.792156862745098,
			},
		},
	},
}

VUI_FUBAR_MAIL = {
	["profiles"] = {
		["Default"] = {
			["detachedTooltip"] = {
			},
			["textformat"] = "text",
		},
	},
}

VUI_FUBAR_PERFORMANCE = {
	["profiles"] = {
		["Default"] = {
			["showRate"] = false,
			["detachedTooltip"] = {
			},
		},
	},
}

VUI_FUBAR_ORA = {
	["profiles"] = {
		["Default"] = {
			["detachedTooltip"] = {
			},
			["showText"] = false,
		},
	},
}

VUI_ORA = {
	["disabled"] = {
		["Default"] = true,
	},
	["disabledModules"] = {
		["Default"] = {
			["Participant/CoolDown"] = true,
			["Participant/Resist"] = true,
			["Optional/MainTank"] = true,
			["Participant/Item"] = true,
			["Optional/CoolDown"] = true,
			["Participant/Assist"] = true,
			["Participant/Durability"] = true,
			["Leader/Item"] = true,
			["Leader/MainTank"] = true,
			["Options Menu"] = true,
			["Leader/Assist"] = true,
			["Participant/Ready"] = true,
			["Optional/Resurrection"] = true,
			["Optional/Zone"] = true,
			["Leader/Resist"] = true,
			["Participant/Resurrection"] = true,
			["Leader/Invite"] = true,
			["Leader/Ready"] = true,
			["Participant/MainTank"] = true,
			["Optional/Version"] = true,
			["Leader/RaidWarn"] = true,
			["Participant/RaidWarn"] = true,
			["Participant/Buff"] = true,
			["Optional/PlayerTarget"] = true,
			["Leader/Durability"] = true,
		},
	},
	["namespaces"] = {
		["Participant/MainTank"] = {
			["profiles"] = {
				["Default"] = {
					["notifydeath"] = true,
				},
			},
		},
		["Optional/MainTank"] = {
			["profiles"] = {
				["Default"] = {
					["tooltips"] = false,
					["posy"] = 748.6837435674463,
					["posx"] = 466.0281061963065,
					["nrmts"] = 5,
					["coloraggro"] = false,
					["backdrop"] = false,
				},
			},
		},
		["Optional/PlayerTarget"] = {
			["profiles"] = {
				["Default"] = {
					["nrpts"] = 6,
					["showpttt"] = false,
					["posy"] = 232.6765632896026,
					["tooltips"] = false,
					["posx"] = 347.5371650665254,
					["showptt"] = false,
					["backdrop"] = false,
					["numbers"] = false,
				},
			},
		},
		["Optional/CoolDown"] = {
			["profiles"] = {
				["Default"] = {
					["posx"] = 619.7100873437083,
					["posy"] = 578.4658954161514,
					["hidden"] = true,
				},
			},
		},
		["inviteleader"] = {
			["profiles"] = {
				["Default"] = {
					["promotes"] = {
					},
				},
			},
		},
		["Leader/Invite"] = {
			["profiles"] = {
				["Default"] = {
					["promotes"] = {
					},
					["keyword"] = "invite",
				},
			},
		},
	},
	["profiles"] = {
		["Default"] = {
			["bartexture"] = "striped",
		},
	},
}

VUI_OSKIN = {
	["profiles"] = {
		["Default"] = {
			["GroupLoot"] = {
				["small"] = true,
			},
			["Tooltips"] = false,
			["ChatEditBox"] = false,
			["BankFrame"] = false,
			["LootFrame"] = false,
		},
	},
}

VUI_SMM = {
	["namespaces"] = {
		["location"] = {
			["profiles"] = {
				["Default"] = {
					["scale"] = 0.8500000000000001,
				},
			},
		},
		["movers"] = {
			["profiles"] = {
				["Default"] = {
					["framePos"] = {
						["QuestTimerFrame"] = {
							["y"] = 835.0082231377395,
							["x"] = 105.9994187129856,
						},
						["QuestWatchFrame"] = {
							["y"] = 831.1131935915602,
							["x"] = 149.2982707379063,
						},
						["DurabilityFrame"] = {
							["y"] = 481.1604507497724,
							["x"] = 667.8527523377825,
						},
						["smmCaptureMover"] = {
							["y"] = 269.8505454152094,
							["x"] = 347.7681045776809,
						},
					},
				},
			},
		},
	},
	["profiles"] = {
		["Default"] = {
			["mapPosition"] = {
				["y"] = 965.9532922177618,
				["x"] = 100.4410699026805,
			},
			["lock"] = true,
		},
	},
}

VUI_TIPBUDDY = {
	["pet_enemy"] = {
		["ebx2"] = "",
		["trg_pl"] = 0,
		["bgcolor"] = {
			["a"] = 0.7999999970197678,
			["r"] = 0.2901960784313725,
			["g"] = 0.07843137254901961,
			["b"] = 0.08235294117647059,
		},
		["xtr"] = 0,
		["trg_en"] = 0,
		["trg"] = 1,
		["fac"] = 1,
		["bff"] = 1,
		["trg_pa"] = 0,
		["cfc"] = 1,
		["cls"] = 1,
		["txt_pvp"] = 0,
		["bgbcolor"] = {
			["a"] = 0,
			["r"] = 0.8,
			["g"] = 0.8,
			["b"] = 0.8980392156862745,
		},
		["hth"] = 1,
		["trg_np"] = 0,
		["c_bdp"] = 0,
		["off"] = 0,
		["gld"] = 1,
		["ebx1"] = "",
		["c_bdb"] = 0,
		["txt_hth"] = 0,
		["txt_mna"] = 0,
		["trg_2l"] = 0,
	},
	["guild"] = {
		["bgcolor"] = {
			["a"] = 0.5999999940395355,
			["r"] = 0.1254901960784314,
			["g"] = 0.1411764705882353,
			["b"] = 0.1294117647058823,
		},
		["bgbcolor"] = {
			["a"] = 0.75,
			["r"] = 0,
			["g"] = 0,
			["b"] = 0,
		},
	},
	["npc_neutral"] = {
		["ebx2"] = "",
		["trg_pl"] = 0,
		["bgcolor"] = {
			["a"] = 0.5499999821186066,
			["r"] = 0.7058823529411764,
			["g"] = 0.6196078431372549,
			["b"] = 0.05490196078431373,
		},
		["xtr"] = 0,
		["trg_en"] = 0,
		["trg"] = 0,
		["fac"] = 0,
		["bff"] = 0,
		["trg_pa"] = 0,
		["cfc"] = 1,
		["cls"] = 1,
		["txt_pvp"] = 0,
		["bgbcolor"] = {
			["a"] = 0,
			["r"] = 0.8,
			["g"] = 0.8,
			["b"] = 0.8980392156862745,
		},
		["hth"] = 0,
		["gld"] = 1,
		["trg_np"] = 1,
		["off"] = 0,
		["txt_hth"] = 0,
		["ebx1"] = "",
		["c_bdb"] = 0,
		["trg_2l"] = 0,
		["c_bdp"] = 0,
		["txt_mna"] = 0,
	},
	["general"] = {
		["anchor_pos"] = "Top Right",
		["bgcolor"] = {
			["a"] = 0.7999999970197678,
			["r"] = 0.01176470588235294,
			["g"] = 0.01176470588235294,
			["b"] = 0.01176470588235294,
		},
		["nonunit_anchor"] = 0,
		["anchored"] = 0,
		["gtt_fade"] = 0,
		["fadetime"] = 0.300000011920929,
		["scalemod"] = 3,
		["opPos_T"] = 1000.24799236328,
		["offset_y"] = 15,
		["delaytime"] = 0.1000000014901161,
		["classcolor"] = 1,
		["gtt_anchored"] = 0,
		["opPos_L"] = 325.5062789892298,
		["reposmods"] = 1,
		["bgbcolor"] = {
			["a"] = 0,
			["r"] = 0,
			["g"] = 0,
			["b"] = 0,
		},
		["hidedefault"] = 1,
		["rankname"] = 0,
		["anchor_vis"] = 0,
		["blizdefault"] = 0,
		["cursorpos"] = "Top",
		["framepos_L"] = 202.0000102621408,
		["framepos_T"] = 399.9999786322549,
		["offset_x"] = 0,
		["diff_bg"] = 0,
		["gtt_scale"] = 1,
		["c"] = 0,
	},
	["textcolors"] = {
		["gld_pvp"] = {
			["a"] = 1,
			["r"] = 0.05,
			["g"] = 0.7,
			["b"] = 0,
		},
		["nam_tpo"] = {
			["a"] = 1,
			["r"] = 0.6,
			["g"] = 0.6,
			["b"] = 0.6,
		},
		["gld_neu"] = {
			["a"] = 1,
			["r"] = 0.9,
			["g"] = 0.7,
			["b"] = 0,
		},
		["gld_hos"] = {
			["a"] = 1,
			["r"] = 0.7,
			["g"] = 0.1,
			["b"] = 0.1,
		},
		["lvl_dif"] = {
			["a"] = 1,
			["r"] = 1,
			["g"] = 1,
			["b"] = 0,
		},
		["other_ctf"] = {
			["a"] = 1,
			["r"] = 0.85,
			["g"] = 0.85,
			["b"] = 0.85,
		},
		["cls_oth"] = {
			["a"] = 1,
			["r"] = 1,
			["g"] = 1,
			["b"] = 1,
		},
		["gld_mte"] = {
			["a"] = 1,
			["r"] = 1,
			["g"] = 0.2,
			["b"] = 1,
		},
		["lvl_imp"] = {
			["a"] = 1,
			["r"] = 1,
			["g"] = 0.1,
			["b"] = 0.1,
		},
		["other_unk"] = {
			["a"] = 1,
			["r"] = 1,
			["g"] = 1,
			["b"] = 1,
		},
		["elite_rar"] = {
			["a"] = 1,
			["r"] = 1,
			["g"] = 1,
			["b"] = 1,
		},
		["gld_tpp"] = {
			["a"] = 1,
			["r"] = 0.8,
			["g"] = 0,
			["b"] = 0,
		},
		["lvl_trv"] = {
			["a"] = 1,
			["r"] = 0.5,
			["g"] = 0.5,
			["b"] = 0.5,
		},
		["nam_hos"] = {
			["a"] = 1,
			["r"] = 0.9,
			["g"] = 0.1,
			["b"] = 0.1,
		},
		["cls_war"] = {
			["a"] = 1,
			["r"] = 0.7,
			["g"] = 0.5,
			["b"] = 0.25,
		},
		["cls_drd"] = {
			["a"] = 1,
			["r"] = 0.9,
			["g"] = 0.55,
			["b"] = 0.1,
		},
		["nam_fri"] = {
			["a"] = 1,
			["r"] = 0.1,
			["g"] = 0.7,
			["b"] = 1,
		},
		["cls_rog"] = {
			["a"] = 1,
			["r"] = 0.95,
			["g"] = 0.9,
			["b"] = 0.1,
		},
		["cls_pri"] = {
			["a"] = 1,
			["r"] = 0.8,
			["g"] = 0.8,
			["b"] = 0.8,
		},
		["gld_fri"] = {
			["a"] = 1,
			["r"] = 0,
			["g"] = 0.5,
			["b"] = 0.8,
		},
		["gld_tpo"] = {
			["a"] = 1,
			["r"] = 0.45,
			["g"] = 0.45,
			["b"] = 0.45,
		},
		["lvl_vdf"] = {
			["a"] = 1,
			["r"] = 1,
			["g"] = 0.5,
			["b"] = 0.25,
		},
		["cls_mag"] = {
			["a"] = 1,
			["r"] = 0.5,
			["g"] = 1,
			["b"] = 1,
		},
		["nam_tpp"] = {
			["a"] = 1,
			["r"] = 1,
			["g"] = 0,
			["b"] = 0,
		},
		["lvl_stn"] = {
			["a"] = 1,
			["r"] = 0.25,
			["g"] = 0.75,
			["b"] = 0.25,
		},
		["gld_cau"] = {
			["a"] = 1,
			["r"] = 0.65,
			["g"] = 0.4,
			["b"] = 0,
		},
		["cls_shm"] = {
			["a"] = 1,
			["r"] = 0.9,
			["g"] = 0.4,
			["b"] = 0.65,
		},
		["cls_wlk"] = {
			["a"] = 1,
			["r"] = 0.5,
			["g"] = 0.26,
			["b"] = 0.9,
		},
		["nam_neu"] = {
			["a"] = 1,
			["r"] = 1,
			["g"] = 0.9,
			["b"] = 0,
		},
		["nam_pvp"] = {
			["a"] = 1,
			["r"] = 0.15,
			["g"] = 0.9,
			["b"] = 0,
		},
		["lvl_sfc"] = {
			["a"] = 1,
			["r"] = 0.85,
			["g"] = 0.85,
			["b"] = 0.85,
		},
		["nam_cau"] = {
			["a"] = 1,
			["r"] = 0.9,
			["g"] = 0.4,
			["b"] = 0,
		},
		["cls_pal"] = {
			["a"] = 1,
			["r"] = 1,
			["g"] = 0.4,
			["b"] = 0.58,
		},
		["elite_bss"] = {
			["a"] = 1,
			["r"] = 1,
			["g"] = 1,
			["b"] = 1,
		},
		["other_rac"] = {
			["a"] = 1,
			["r"] = 1,
			["g"] = 1,
			["b"] = 1,
		},
		["cls_hun"] = {
			["a"] = 0.9,
			["r"] = 0.1,
			["g"] = 0.85,
			["b"] = 0.1,
		},
		["other_crp"] = {
			["a"] = 1,
			["r"] = 0.5,
			["g"] = 0.5,
			["b"] = 0.5,
		},
	},
	["npc_enemy"] = {
		["ebx2"] = "",
		["trg_pl"] = 0,
		["bgcolor"] = {
			["a"] = 0.78,
			["r"] = 0.35,
			["g"] = 0.09,
			["b"] = 0.13,
		},
		["xtr"] = 0,
		["trg_en"] = 0,
		["trg"] = 1,
		["fac"] = 0,
		["bff"] = 0,
		["trg_pa"] = 0,
		["cfc"] = 1,
		["cls"] = 1,
		["txt_pvp"] = 0,
		["bgbcolor"] = {
			["a"] = 0,
			["r"] = 0.8,
			["g"] = 0.8,
			["b"] = 0.8980392156862745,
		},
		["hth"] = 1,
		["gld"] = 1,
		["trg_np"] = 0,
		["off"] = 0,
		["txt_hth"] = 0,
		["ebx1"] = "",
		["c_bdb"] = 0,
		["trg_2l"] = 0,
		["c_bdp"] = 0,
		["txt_mna"] = 0,
	},
	["pc_friend"] = {
		["ebx2"] = "",
		["trg_pl"] = 0,
		["bgcolor"] = {
			["a"] = 0.75,
			["r"] = 0,
			["g"] = 0,
			["b"] = 0,
		},
		["rnk"] = 1,
		["xtr"] = 0,
		["trg_en"] = 0,
		["trg"] = 1,
		["fac"] = 0,
		["bff"] = 0,
		["trg_pa"] = 0,
		["cfc"] = 0,
		["cls"] = 1,
		["txt_pvp"] = 0,
		["bgbcolor"] = {
			["a"] = 0,
			["r"] = 0.8901960784313725,
			["g"] = 0.8901960784313725,
			["b"] = 1,
		},
		["gld"] = 1,
		["trg_np"] = 0,
		["trg_2l"] = 0,
		["rac"] = 0,
		["txt_hth"] = 0,
		["off"] = 0,
		["txt_mna"] = 0,
		["ebx1"] = "",
		["c_bdb"] = 0,
		["c_bdp"] = 0,
		["hth"] = 1,
		["rnm"] = 0,
	},
	["version"] = "2.22",
	["npc_friend"] = {
		["ebx2"] = "",
		["trg_pl"] = 0,
		["bgcolor"] = {
			["a"] = 0.5499999821186066,
			["r"] = 0.07058823529411765,
			["g"] = 0.2862745098039216,
			["b"] = 0.0392156862745098,
		},
		["xtr"] = 0,
		["trg_en"] = 0,
		["trg"] = 0,
		["fac"] = 0,
		["bff"] = 0,
		["trg_pa"] = 0,
		["cfc"] = 1,
		["cls"] = 1,
		["txt_pvp"] = 0,
		["bgbcolor"] = {
			["a"] = 0,
			["r"] = 0.8,
			["g"] = 0.8,
			["b"] = 0.8980392156862745,
		},
		["hth"] = 0,
		["gld"] = 1,
		["trg_np"] = 0,
		["off"] = 0,
		["txt_hth"] = 0,
		["ebx1"] = "",
		["c_bdb"] = 0,
		["txt_mna"] = 0,
		["c_bdp"] = 0,
		["trg_2l"] = 0,
	},
	["corpse"] = {
		["ebx2"] = "",
		["trg_pl"] = 0,
		["bgcolor"] = {
			["a"] = 0.78,
			["r"] = 0.09,
			["g"] = 0.09,
			["b"] = 0.19,
		},
		["xtr"] = 1,
		["trg_en"] = 0,
		["trg"] = 0,
		["fac"] = 1,
		["bff"] = 0,
		["trg_pa"] = 0,
		["cfc"] = 1,
		["cls"] = 1,
		["txt_pvp"] = 0,
		["bgbcolor"] = {
			["a"] = 0,
			["r"] = 0.8,
			["g"] = 0.8,
			["b"] = 0.8980392156862745,
		},
		["hth"] = 0,
		["gld"] = 1,
		["off"] = 0,
		["trg_np"] = 0,
		["ebx1"] = "",
		["c_bdb"] = 0,
		["txt_hth"] = 0,
		["c_bdp"] = 0,
		["txt_mna"] = 0,
	},
	["pet_friend"] = {
		["ebx2"] = "",
		["trg_pl"] = 0,
		["bgcolor"] = {
			["a"] = 0.78,
			["r"] = 0.14,
			["g"] = 0.29,
			["b"] = 0.24,
		},
		["xtr"] = 0,
		["trg_en"] = 0,
		["trg"] = 1,
		["fac"] = 1,
		["bff"] = 1,
		["trg_pa"] = 0,
		["cfc"] = 0,
		["cls"] = 1,
		["txt_pvp"] = 0,
		["bgbcolor"] = {
			["a"] = 0,
			["r"] = 0.8,
			["g"] = 0.8,
			["b"] = 0.8980392156862745,
		},
		["hth"] = 0,
		["gld"] = 1,
		["trg_np"] = 0,
		["off"] = 0,
		["txt_hth"] = 0,
		["ebx1"] = "",
		["c_bdb"] = 0,
		["trg_2l"] = 0,
		["c_bdp"] = 0,
		["txt_mna"] = 0,
	},
	["pc_enemy"] = {
		["ebx2"] = "",
		["trg_pl"] = 0,
		["bgcolor"] = {
			["a"] = 0.78,
			["r"] = 0.3686274509803922,
			["g"] = 0.1215686274509804,
			["b"] = 0.07058823529411765,
		},
		["rnk"] = 1,
		["xtr"] = 0,
		["trg_en"] = 0,
		["trg"] = 1,
		["fac"] = 1,
		["bff"] = 1,
		["trg_pa"] = 0,
		["cfc"] = 0,
		["cls"] = 1,
		["txt_pvp"] = 0,
		["bgbcolor"] = {
			["a"] = 0,
			["r"] = 0.8,
			["g"] = 0.8,
			["b"] = 0.8980392156862745,
		},
		["gld"] = 1,
		["trg_np"] = 0,
		["hth"] = 1,
		["rac"] = 1,
		["txt_hth"] = 0,
		["off"] = 0,
		["rnm"] = 0,
		["ebx1"] = "",
		["c_bdb"] = 0,
		["trg_2l"] = 0,
		["c_bdp"] = 0,
		["txt_mna"] = 0,
	},
	["pc_party"] = {
		["ebx2"] = "",
		["trg_pl"] = 0,
		["bgcolor"] = {
			["a"] = 1,
			["r"] = 0,
			["g"] = 0,
			["b"] = 0,
		},
		["rnk"] = 1,
		["xtr"] = 0,
		["trg_en"] = 0,
		["trg"] = 1,
		["fac"] = 0,
		["bff"] = 1,
		["trg_pa"] = 0,
		["cfc"] = 0,
		["cls"] = 1,
		["txt_pvp"] = 0,
		["bgbcolor"] = {
			["a"] = 0.300000011920929,
			["r"] = 0.8901960784313725,
			["g"] = 0.8901960784313725,
			["b"] = 1,
		},
		["gld"] = 1,
		["trg_np"] = 0,
		["trg_2l"] = 0,
		["rac"] = 0,
		["txt_hth"] = 0,
		["off"] = 0,
		["c_bdp"] = 0,
		["ebx1"] = "",
		["c_bdb"] = 0,
		["txt_mna"] = 0,
		["hth"] = 1,
		["rnm"] = 0,
	},
}

VUI_TOTEMTIMER = {
	["warn"] = "on",
	["align"] = "left",
	["dragging"] = 0,
	["flash"] = 10,
	["show"] = 1,
	["notify"] = "on",
	["time"] = "ct",
	["lock"] = 1,
	["order"] = {
		[1] = "Fire",
		[2] = "Earth",
		[3] = "Air",
		[4] = "Water",
	},
	["style"] = "sticky",
	["arrange"] = "horizontal",
	["Default"] = {
		["warningTime"] = 10,
		["expireMsg"] = "is Destroyed",
		["expireColor"] = {
			[1] = 1,
			[2] = 1,
			[3] = 0,
		},
		["warningMsg"] = "is Expiring.",
		["warningColor"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
		},
	},
}

VUI_KTM = {
	["autohide"] = true,
	["gui"] = {
		["state"] = {
			["view"] = "raid",
			["max"] = true,
			["pinned"] = true,
			["closed"] = true,
			["min"] = false,
			["raid"] = true,
			["minmax"] = "max",
			["self"] = false,
		},
		["version"] = 235,
		["options"] = {
			["self"] = {
				["columnVis"] = {
					["dam"] = true,
					["pc"] = true,
					["name"] = true,
					["threat"] = true,
					["rage"] = true,
					["hits"] = true,
				},
				["sortColumn"] = "threat",
				["abbreviate"] = false,
				["hideZeroRows"] = true,
				["sortDown"] = true,
				["stringVis"] = {
					["threat"] = true,
				},
			},
			["scale"] = 1,
			["raid"] = {
				["abbreviate"] = true,
				["hideZeroRows"] = true,
				["hideBottomBar"] = false,
				["rows"] = 9,
				["columnVis"] = {
					["threat"] = false,
					["name"] = true,
					["pc"] = true,
				},
				["showAggroGain"] = false,
				["resize"] = false,
				["stringVis"] = {
					["tdef"] = false,
					["pc"] = false,
					["rank"] = false,
				},
			},
			["buttonVis"] = {
				["min"] = {
					["targ"] = false,
					["close"] = true,
					["view"] = false,
					["opt"] = true,
					["pin"] = false,
					["minmax"] = true,
					["clear"] = false,
				},
				["max"] = {
					["targ"] = true,
					["close"] = true,
					["view"] = false,
					["opt"] = true,
					["pin"] = false,
					["minmax"] = true,
					["clear"] = true,
				},
			},
		},
	},
}

VUI_SPELLALERT = {
	["retarget_on"] = 1,
	["misc"] = 1,
	["color"] = {
		["bu"] = {
			["r"] = 0,
			["g"] = 1,
			["b"] = 0,
		},
		["to"] = {
			["r"] = 0.5,
			["g"] = 0.5,
			["b"] = 0.5,
		},
		["at"] = {
			["r"] = 1,
			["g"] = 0,
			["b"] = 0,
		},
		["he"] = {
			["r"] = 1,
			["g"] = 1,
			["b"] = 0,
		},
		["em"] = {
			["r"] = 1,
			["g"] = 0.6,
			["b"] = 0,
		},
	},
	["drag"] = 5,
	["cc"] = 1,
	["damage"] = 1,
	["zoom"] = 37,
	["radio"] = 1,
	["emote_on"] = 1,
	["on"] = 1,
	["version"] = 1.5,
	["holdTime"] = 1.5,
	["livingBomb"] = 1,
	["heals"] = 1,
	["dispelable"] = 1,
	["shadow"] = 1,
	["targetonly"] = 1,
	["pos"] = -350,
}

VUI_SCTC = {
	["disabled"] = {
		["Revenge"] = true,
		["Throw"] = true,
		["Shoot Crossbow"] = true,
		["Shoot Bow"] = true,
	},
	["color"] = {
		["r"] = 1,
		["g"] = 1,
		["b"] = 1,
	},
	["on"] = true,
	["version"] = "1.4.2",
	["members"] = {
	},
	["wformat"] = "[%s Ready In 10]",
	["format"] = "[%s Ready]",
	["crit"] = 1,
	["groups"] = {
	},
}

VUI_SWS = {
	["SW_IconPos"] = 239,
	["QuickOptCount"] = 5,
	["ReportAmount"] = 3,
	["TL_SafeMode"] = true,
	["SyncBCTarget"] = "SW_BarSyncFrame_OptRaid",
	["lastWOWBuild"] = "1.12.15875Sep 19 2006",
	["RepTarget"] = "SW_RepTo_Say",
	["IsRunning"] = true,
	["OPT_ShowMainWinDPS"] = 1,
	["InfoSettings"] = {
		[1] = {
			["CF"] = 1,
			["OT"] = "DD",
			["BC"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 1,
			},
			["OTF"] = "Damage Done",
			["ShowPercent"] = 1,
			["UCC"] = 1,
			["TV"] = "",
			["OC"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 0.4800000190734863,
			},
			["SF"] = "SW_Filter_EverGroup",
			["selSchool"] = 0,
			["PF"] = "SW_PF_MM",
			["ShowRank"] = 1,
			["COLC"] = 2,
			["ShowNumber"] = 1,
			["BFC"] = {
				[1] = 1,
				[2] = 1,
				[3] = 1,
				[4] = 1,
			},
			["IN"] = 1,
			["BFS"] = 10,
			["BT"] = 9,
			["BH"] = 9,
		},
		[2] = {
			["IN"] = 7,
			["OT"] = "DI",
			["BC"] = {
				[1] = 1,
				[2] = 1,
				[3] = 1,
				[4] = 1,
			},
			["OTF"] = "Damage Done (Info)",
			["ShowPercent"] = 1,
			["TV"] = "Virose",
			["BH"] = 10,
			["BFS"] = 10,
			["BT"] = 10,
			["ShowRank"] = 1,
			["ShowNumber"] = 1,
			["BFC"] = {
				[1] = 1,
				[2] = 1,
				[3] = 1,
				[4] = 1,
			},
			["COLC"] = 1,
			["OC"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 0.4800000190734863,
			},
			["CF"] = 1,
		},
		[3] = {
			["CF"] = 1,
			["OT"] = "DP",
			["BC"] = {
				[1] = 0,
				[2] = 0.8,
				[3] = 0,
				[4] = 1,
			},
			["OTF"] = "Damage Per Second",
			["ShowPercent"] = 1,
			["UCC"] = 1,
			["OC"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 0.4800000190734863,
			},
			["BFS"] = 10,
			["COLC"] = 2,
			["ShowRank"] = 1,
			["BH"] = 9,
			["IN"] = 17,
			["ShowNumber"] = 1,
			["BFC"] = {
				[1] = 1,
				[2] = 1,
				[3] = 1,
				[4] = 1,
			},
			["SF"] = "SW_Filter_EverGroup",
			["BT"] = 9,
			["HealEff"] = true,
			["HealInF"] = true,
		},
		[4] = {
			["IN"] = 2,
			["OT"] = "EH",
			["BC"] = {
				[1] = 0,
				[2] = 0.8,
				[3] = 0,
				[4] = 1,
			},
			["OTF"] = "Effective Healing",
			["HealOH"] = false,
			["ShowPercent"] = 1,
			["UCC"] = 1,
			["OC"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 0.4600000381469727,
			},
			["SF"] = "SW_Filter_EverGroup",
			["COLC"] = 2,
			["ShowRank"] = 1,
			["BH"] = 9,
			["BT"] = 9,
			["ShowNumber"] = 1,
			["BFC"] = {
				[1] = 1,
				[2] = 1,
				[3] = 1,
				[4] = 1,
			},
			["CF"] = 1,
			["BFS"] = 10,
			["HealEff"] = true,
			["HealInF"] = true,
		},
		[5] = {
			["CF"] = 1,
			["OT"] = "OH",
			["BC"] = {
				[1] = 0,
				[2] = 0.8,
				[3] = 0,
				[4] = 1,
			},
			["HealEff"] = false,
			["HealOH"] = true,
			["ShowPercent"] = 1,
			["UCC"] = 1,
			["OC"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
				[4] = 0.449999988079071,
			},
			["BFS"] = 10,
			["COLC"] = 2,
			["ShowRank"] = 1,
			["BH"] = 9,
			["SF"] = "SW_Filter_EverGroup",
			["ShowNumber"] = 1,
			["BFC"] = {
				[1] = 1,
				[2] = 1,
				[3] = 1,
				[4] = 1,
			},
			["BT"] = 9,
			["IN"] = 2,
			["OTF"] = "Over Healing",
			["HealInF"] = true,
		},
	},
	["BFLocked"] = true,
	["Colors"] = {
		["HUNTER"] = {
			[1] = 0.67,
			[2] = 0.83,
			[3] = 0.45,
			[4] = 1,
		},
		["WARRIOR"] = {
			[1] = 0.78,
			[2] = 0.61,
			[3] = 0.43,
			[4] = 1,
		},
		["SHAMAN"] = {
			[1] = 0.96,
			[2] = 0.55,
			[3] = 0.73,
			[4] = 1,
		},
		["MAGE"] = {
			[1] = 0.41,
			[2] = 0.8,
			[3] = 0.94,
			[4] = 1,
		},
		["DRUID"] = {
			[1] = 1,
			[2] = 0.49,
			[3] = 0.04,
			[4] = 1,
		},
		["Damage"] = {
			[1] = 0.6470588235294118,
			[2] = 0.6470588235294118,
			[3] = 0.6470588235294118,
			[4] = 1,
		},
		["TitleBarsFont"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["MainWinBack"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["PRIEST"] = {
			[1] = 1,
			[2] = 1,
			[3] = 1,
			[4] = 1,
		},
		["Heal"] = {
			[1] = 0.1294117647058823,
			[2] = 0.6941176470588235,
			[3] = 0.5215686274509804,
			[4] = 1,
		},
		["WARLOCK"] = {
			[1] = 0.58,
			[2] = 0.51,
			[3] = 0.79,
			[4] = 1,
		},
		["ROGUE"] = {
			[1] = 1,
			[2] = 0.96,
			[3] = 0.41,
			[4] = 1,
		},
		["PALADIN"] = {
			[1] = 0.96,
			[2] = 0.55,
			[3] = 0.73,
			[4] = 1,
		},
		["TitleBars"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["Backdrops"] = {
			[1] = 0.6980392156862745,
			[2] = 0.6980392156862745,
			[3] = 1,
			[4] = 0,
		},
	},
	["BarFrames"] = {
		["SW_BarFrame1"] = {
			["Docked"] = {
				[1] = 1,
			},
			["Selected"] = 1,
		},
	},
	["SW_TL_AutoDelete"] = true,
	["SW_IconPosR"] = 90,
	["LAST_V_RUN"] = "2.0 Beta.7",
	["SHOWMAIN"] = true,
}

VUI_SCT = {
			["SCTD_SHOWRESIST"] = 1,
			["SCTD_SHOWPET"] = 1,
			["HEALFILTER"] = 150,
			["SCTD_ENABLED"] = 1,
			["ANIMATIONSPEED"] = 10,
			["SCTD_SPELLCOLOR"] = 1,
			["SCTD_SHOWTARGETS"] = false,
			["SCTD_SHOWDMGTYPE"] = false,
			["FRAMESDATA"] = {
				[1] = {
					["TEXTSIZE"] = 22,
					["XOFFSET"] = 210,
					["YOFFSET"] = 210,
					["DIRECTION"] = 1,
				},
				[2] = {
					["TEXTSIZE"] = 20,
					["YOFFSET"] = -40,
					["XOFFSET"] = -290,
				},
				[3] = {
					["ANITYPE"] = 1,
					["ALPHA"] = 100,
					["DIRECTION"] = false,
					["FADE"] = 1.5,
					["FONTSHADOW"] = 2,
					["TEXTSIZE"] = 33,
					["FONT"] = 1,
					["ANISIDETYPE"] = 1,
					["YOFFSET"] = 0,
					["XOFFSET"] = 290,
				},
				[10] = {
					["MSGFONT"] = 3,
					["MSGFONTSHADOW"] = 3,
					["MSGSIZE"] = 33,
					["MSGYOFFSET"] = 190,
				},
			},
			["COLORS"] = {
				["SCTD_SHOWMELEE"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["SCTD_SHOWSPELL"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["SCTD_SHOWPET"] = {
					["r"] = 0.6,
					["g"] = 0.6,
					["b"] = 0,
				},
				["SCTD_SHOWCOLORCRIT"] = {
					["r"] = 0.2,
					["g"] = 0.4,
					["b"] = 0.6,
				},
				["SCTD_SHOWPERIODIC"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
			},
			["SHOWCOMBAT"] = 1,
			["SCTD_SHOWMELEE"] = 1,
			["SCTD_DMGFONT"] = 1,
			["MOVEMENT"] = 1,
			["SCTD_SHOWSPELL"] = 1,
			["SCTD_TARGET"] = false,
			["SCTD_USESCT"] = 1,
			["MANAFILTER"] = 100,
			["SCTD_SHOWPERIODIC"] = 1,
			["SCTD_FLAGDMG"] = false,
			["CRITS"] = {
				["SHOWDEBUFF"] = 1,
				["SHOWPOWER"] = false,
				["SHOWRESIST"] = 1,
				["SHOWFADE"] = false,
				["SHOWSELFHEAL"] = false,
				["SHOWDODGE"] = false,
				["SHOWCOMBOPOINTS"] = 1,
				["SHOWABSORB"] = 1,
				["SHOWCOMBAT"] = 1,
			},
			["SHOWFADE"] = 1,
			["SHOWCOMBOPOINTS"] = 1,
			["FRAMES"] = {
				["SHOWMISS"] = 2,
				["SHOWBLOCK"] = 2,
				["SHOWDODGE"] = 2,
				["SHOWREP"] = 2,
				["SHOWCOMBAT"] = 10,
				["SHOWBUFF"] = 2,
				["SHOWHONOR"] = 2,
				["SHOWPARRY"] = 2,
				["SHOWLOWHP"] = 10,
				["SHOWLOWMANA"] = 10,
				["SHOWRESIST"] = 10,
				["SHOWSPELL"] = 2,
				["SHOWHIT"] = 2,
				["SHOWFADE"] = 2,
				["SHOWSELFHEAL"] = 10,
				["SHOWEXECUTE"] = 10,
				["SHOWCOMBOPOINTS"] = 2,
				["SHOWDEBUFF"] = 2,
				["SHOWABSORB"] = 10,
			},
			["SCTD_STICKYCRIT"] = 1,
			["SCTD_SHOWSPELLNAME"] = 1,
			["SCTD_SHOWCOLORCRIT"] = 1,
		}
		